M48
; DRILL file {KiCad (6.0.1)} date Wed Jun 15 10:15:08 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-15T10:15:08-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.3Y-2.25
X5.3Y-3.5
X6.5354Y-3.502
X6.54Y-2.25
T0
M30
